/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView;

/**
 *
 * @author Olive
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    VitalSignHistory history;
    
    public ViewJPanel(VitalSignHistory vs) {
        initComponents();
        this.history = vs;
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
        model.setRowCount(0);
        
        for(VitalSign vs : history.getHistory()) {
            Object[] row = new Object[5];
            row[0] = vs;
            row[1] = vs.getTemperature();
            row[2] = vs.getBloodPressure();
            row[3] = vs.getPulse();
            row[4] = vs.isIsConscious();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        lblDate = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblCon = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        filedPulse = new javax.swing.JTextField();
        filedDate = new javax.swing.JTextField();
        filedTemp = new javax.swing.JTextField();
        filedBP = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblTitle.setText("View Vital Sign History");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Conscious"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 630, 250));

        lblDate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 80, 40));

        lblTemp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblTemp.setText("Temperature");
        add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 120, 20));

        lblCon.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblCon.setText("Consicouse");
        add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, 60));

        btnSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 130, 50));

        lblBP.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblBP.setText("Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, 60));

        lblPulse.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, -1, 60));

        filedPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedPulseActionPerformed(evt);
            }
        });
        add(filedPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 190, 30));

        filedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedDateActionPerformed(evt);
            }
        });
        add(filedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 190, 30));

        filedTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedTempActionPerformed(evt);
            }
        });
        add(filedTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 190, 30));

        filedBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedBPActionPerformed(evt);
            }
        });
        add(filedBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 190, 30));
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 120, 30));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //        String date;
        //        float temperature;
        //        double bloodPressure;
        //        int pulse;
        //        boolean isConscious;
    }//GEN-LAST:event_btnSaveActionPerformed

    private void filedPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedPulseActionPerformed

    private void filedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedDateActionPerformed

    private void filedTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedTempActionPerformed

    private void filedBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedBPActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        history.deleteVital(selectedVital);
        
        JOptionPane.showMessageDialog(this, "VitalSign Deleted", "Success", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        
        filedDate.setText("");
        filedBP.setText("");
        filedPulse.setText("");
        filedTemp.setText("");
        lblStatus.setText("");

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow, 0);
        
        if (selectedVital != null) {
            filedDate.setText(selectedVital.getDate());
            filedTemp.setText(String.valueOf(selectedVital.getTemperature()));
            filedBP.setText(String.valueOf(selectedVital.getBloodPressure()));
            filedPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if (selectedVital.isIsConscious()) {
                lblStatus.setText("Yes");
            } else {
                lblStatus.setText("No");
            }
        }
        
        populateTable();
        
       

    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField filedBP;
    private javax.swing.JTextField filedDate;
    private javax.swing.JTextField filedPulse;
    private javax.swing.JTextField filedTemp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVital;
    // End of variables declaration//GEN-END:variables

    
}
