/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author Olive
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    VitalSignHistory history;
    
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDate = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        lblCon = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblCreateVital = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        filedPulse = new javax.swing.JTextField();
        filedDate = new javax.swing.JTextField();
        filedTemp = new javax.swing.JTextField();
        filedBP = new javax.swing.JTextField();
        btnNo = new javax.swing.JRadioButton();
        btnYes = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 80, 40));

        lblTemp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTemp.setText("Temperature");
        add(lblTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, -1));

        lblCon.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblCon.setText("Consicouse");
        add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 60));

        btnSave.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 130, 50));

        lblCreateVital.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblCreateVital.setText("Create Vital Sign");
        add(lblCreateVital, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 200, -1));

        lblBP.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblBP.setText("Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, 60));

        lblPulse.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 60));

        filedPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedPulseActionPerformed(evt);
            }
        });
        add(filedPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 190, 30));

        filedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedDateActionPerformed(evt);
            }
        });
        add(filedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 190, 30));

        filedTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedTempActionPerformed(evt);
            }
        });
        add(filedTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 190, 30));

        filedBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filedBPActionPerformed(evt);
            }
        });
        add(filedBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 190, 30));

        buttonGroup1.add(btnNo);
        btnNo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnNo.setText("No");
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        buttonGroup1.add(btnYes);
        btnYes.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        //        String date;
        //        float temperature;
        //        double bloodPressure;
        //        int pulse;
        //        boolean isConscious;

        VitalSign vs = history.addNewVital();
        String date = filedDate.getText();
        float temp = Float.parseFloat(filedTemp.getText());
        double bp = Double.parseDouble(filedBP.getText());
        int pulse = Integer.parseInt(filedPulse.getText());
        boolean con = btnYes.isSelected();

        vs.setDate(date);
        vs.setBloodPressure(bp);
        vs.setIsConscious(con);
        vs.setPulse(pulse);
        vs.setTemperature(temp);

        JOptionPane.showMessageDialog(this, "New VitalSign added", "Success", JOptionPane.INFORMATION_MESSAGE);

        filedDate.setText("");
        filedBP.setText("");
        filedPulse.setText("");
        filedTemp.setText("");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void filedPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedPulseActionPerformed

    private void filedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedDateActionPerformed

    private void filedTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedTempActionPerformed

    private void filedBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filedBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filedBPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField filedBP;
    private javax.swing.JTextField filedDate;
    private javax.swing.JTextField filedPulse;
    private javax.swing.JTextField filedTemp;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblCreateVital;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemp;
    // End of variables declaration//GEN-END:variables
}
