/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import Model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Olive
 */
public class AccountMngWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountMngWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    AccountDirectory acctDirectory;
    
    public AccountMngWorkAreaJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        acctDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAcct = new javax.swing.JButton();
        btnMngAcct = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateAcct.setText("Create Account");
        btnCreateAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAcctActionPerformed(evt);
            }
        });
        add(btnCreateAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnMngAcct.setText("Manage Account");
        btnMngAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngAcctActionPerformed(evt);
            }
        });
        add(btnMngAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAcctActionPerformed
        // TODO add your handling code here:
        CreateAccountJPanel panel = new CreateAccountJPanel(userProcessContainer, acctDirectory);
        userProcessContainer.add("CreateAccountJPanel" , panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateAcctActionPerformed

    private void btnMngAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngAcctActionPerformed
        // TODO add your handling code here:
        
        ManageAccountsJPanel panel = new ManageAccountsJPanel(userProcessContainer, acctDirectory);
        userProcessContainer.add("ManagementAccountsJPanel" , panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngAcctActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcct;
    private javax.swing.JButton btnMngAcct;
    // End of variables declaration//GEN-END:variables
}
