/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

/**
 *
 * @author Olive
 */
public class AccountMngWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountMngWorkAreaJPanel
     */
    public AccountMngWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateAcct = new javax.swing.JButton();
        btnMngAcct = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateAcct.setText("Create Account");
        add(btnCreateAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        btnMngAcct.setText("Manage Account");
        add(btnMngAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAcct;
    private javax.swing.JButton btnMngAcct;
    // End of variables declaration//GEN-END:variables
}
