/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

import Model.Account;
import Model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Olive
 */
public class CreateAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAccountJPanel
     */
    
    JPanel userProcessContainer;
    AccountDirectory acctDirectory;
    
    public CreateAccountJPanel(JPanel container, AccountDirectory directory) {
        initComponents();
        userProcessContainer = container;
        acctDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAcct = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblRouting = new javax.swing.JLabel();
        lblAcctNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtRouting = new javax.swing.JTextField();
        txtAcctNumber = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateAcct.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblCreateAcct.setText("Create Account");
        add(lblCreateAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        lblBalance.setText("Balance");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        lblRouting.setText("Routing Number");
        add(lblRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblAcctNumber.setText("Account Number");
        add(lblAcctNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 20));

        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));
        add(txtBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 190, 30));
        add(txtRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 30));
        add(txtAcctNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 30));
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 190, 30));

        jButton1.setText("<<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        int balance;
        
        String routing = txtRouting.getText();
        String acctNumber = txtAcctNumber.getText();
        String bankName = txtBankName.getText();
        
        if (routing.isBlank() || acctNumber.isBlank() || acctNumber.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            balance = Integer.parseInt(txtBalance.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please check the balance input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Account a = acctDirectory.addAccount();
        a.setRoutingNumber(routing);
        a.setAccountNumber(acctNumber);
        a.setBalance(balance);
        a.setBankName(bankName);
        
        JOptionPane.showMessageDialog(this, "Created!", "Success", JOptionPane.INFORMATION_MESSAGE);
        txtAcctNumber.setText("");
        txtBalance.setText("");
        txtBankName.setText("");
        txtRouting.setText("");
        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAcctNumber;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCreateAcct;
    private javax.swing.JLabel lblRouting;
    private javax.swing.JTextField txtAcctNumber;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRouting;
    // End of variables declaration//GEN-END:variables
}
