/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AccountManager;

/**
 *
 * @author Olive
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
    public ViewAccountJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewAcct = new javax.swing.JLabel();
        lblRouting = new javax.swing.JLabel();
        lblAcctNumber = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        txtRouting = new javax.swing.JTextField();
        txtAcctNumber = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewAcct.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblViewAcct.setText("View Account");
        add(lblViewAcct, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        lblRouting.setText("Routing Number");
        add(lblRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        lblAcctNumber.setText("Account Number");
        add(lblAcctNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, 20));

        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));
        add(txtRouting, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 250, 30));
        add(txtAcctNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 250, 30));
        add(txtBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 250, 30));

        jButton1.setText("<<< Back");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnUpdate.setText("Update");
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        btnSave.setText("Save");
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAcctNumber;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblRouting;
    private javax.swing.JLabel lblViewAcct;
    private javax.swing.JTextField txtAcctNumber;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtRouting;
    // End of variables declaration//GEN-END:variables
}
